site_name: Midnight City – Règlements
site_url: https://docs.midnightcityrp.com
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: slate
      primary: green
      accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  logo: assets/logo_serveur.png
  favicon: assets/images/favicon.ico
plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - def_list
  - attr_list
  - tables
nav:
  - Accueil: index.md
  - À propos:
    - Notre vision, mission & objectifs: about-us/notre-vision-mission-and-nos-objectifs.md
    - Nos valeurs: about-us/nos-valeurs.md
  - Bien démarrer:
    - Guide du nouvel arrivant: bien-demarrer-sur-vespucci/guide-du-nouvel-arrivant.md
  - Règlement général:
    - Donations & contreparties: reglement-general/donations-et-contreparties.md
    - Informations pour les streamers: reglement-general/informations-pour-les-streamers.md
    - Généralités & Termes:
      - Accueil: reglement-general/generalites-et-termes/README.md
      - Règles concernant les comas: reglement-general/generalites-et-termes/regles-concernant-les-comas.md
      - Safezones: reglement-general/generalites-et-termes/safezones.md
      - Termes RP: reglement-general/generalites-et-termes/termes-rp.md
    - Interdictions:
      - Accueil: reglement-general/interdictions/README.md
      - Interdictions des citoyens non whitelist: reglement-general/interdictions/interdictions-des-citoyens-non-whitelist.md
  - Règlement spécifique:
    - Code pénal: reglement-specifique/code-penal.md
    - DEFCONs: reglement-specifique/defcons.md
    - Règlement des jobs: reglement-specifique/reglement-de-jobs.md
    - Règlement des criminels: reglement-specifique/reglement-des-criminels.md
  - Équipe:
    - Découvrir l’équipe du staff:
      - Accueil: team/decouvrez-lequipe-du-staff/README.md
      - Administrateurs: team/decouvrez-lequipe-du-staff/administrateurs.md
      - Modérateurs: team/decouvrez-lequipe-du-staff/moderateurs.md
      - Pôle décisionnaire: team/decouvrez-lequipe-du-staff/pole-decisionnaire.md
      - Support: team/decouvrez-lequipe-du-staff/support.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ton-invite

extra_css:
  - assets/stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2025 Midnight City RP
